log_path = "logs/log.txt"             # log file
reports_path = "logs/reports.txt"     # file to report illegal or failed attempts to use admin features
tmp_token_path = "access/tmp_token.txt"  # file with the temporary auth token to unlock admin features
token_path = "access/token.txt"          # file with the secret bot token
sendall_path = "access/sendall.txt"      # file with the text for the send_all feature
type_path = "../common/type.txt"      # file with the help text
help_path = "../common/help.txt"      # file with the help text
about_path = "../common/about.txt"    # file with the about text
expired_path = "../common/expired.txt"  # file with the expired text
